---
- name: Restart web server
  service:
    name: "{{ web_server_config[web_server].service_name }}"
    state: restarted
    enabled: true
  listen: "Restart web server"

- name: Restart nginx server
  service:
    name: nginx
    state: restarted
    enabled: true
  listen: "Restart nginx server"

- name: Update CA trust
  command: update-ca-trust extract
  listen: "Update CA trust"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemd daemon reload"
