# web_ssl_management/tasks/backup_nginx.yml
---
- name: Find Nginx SSL config files on {{ ansible_fqdn }}
  ansible.builtin.find:
    paths: "{{ item | dirname }}"
    patterns: "{{ item | basename }}"
  loop: "{{ web_server_config.nginx.ssl_conf_files }}"
  register: nginx_conf_files
  when: web_server_config is defined and web_server_config.nginx is defined

- name: Read Nginx SSL config files
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  loop: "{{ nginx_conf_files.results | json_query('[].files[*]') | flatten }}"
  register: ssl_conf_contents
  when: nginx_conf_files.results | length > 0
  ignore_errors: true

- name: Extract SSL file paths from Nginx configs on {{ ansible_fqdn }}
  ansible.builtin.set_fact:
    ssl_paths: "{{ combined_content | regex_findall('(?m)^\\s*(ssl_certificate|ssl_certificate_key)\\s+([^;]+)') | map('last') | map('trim') | list | unique }}"
  vars:
    combined_content: "{{ ssl_conf_contents.results | select('succeeded') | map(attribute='content') | map('b64decode') | join('\n') }}"
  when: ssl_conf_contents.results | select('succeeded') | list | length > 0

- name: Set existing certificate and key paths
  ansible.builtin.set_fact:
    existing_cert_file: '{{ (ssl_paths | select("match", ".*\\.(crt|pem)$") | first) | default(cert_dir ~ "/fullchain.pem") }}'
    existing_key_file: '{{ (ssl_paths | select("match", ".*\\.key$") | first) | default(key_dir ~ "/" ~ ansible_fqdn ~ ".key") }}'
  vars:
    cert_dir: "{{ web_server_config.nginx.cert_dir }}"
    key_dir: "{{ web_server_config.nginx.key_dir }}"

- name: Get stats of existing nginx certificates on {{ ansible_fqdn }}
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "{{ existing_cert_file }}"
    - "{{ existing_key_file }}"
  register: existing_stats

- name: Backup existing nginx certificates on {{ ansible_fqdn }}
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ backup_dir }}/{{ item.path | basename }}.bkp_{{ ansible_date_time.iso8601_basic_short }}"
    remote_src: true
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ existing_stats.results[0].stat.path }}", mode: '0644' }
    - { path: "{{ existing_stats.results[1].stat.path }}", mode: '0600' }
  when: existing_stats.results[0].stat.exists and existing_stats.results[1].stat.exists

