- name: Verify server responds with content from {{ ansible_fqdn }}
  uri:
    url: "https://{{ ansible_fqdn }}"
    method: GET
    return_content: true
    status_code: 200
  register: uri_result
  retries: 5
  delay: 5
  until: "uri_result.content | length > 0"
  delegate_to: "{{ ansible_fqdn }}"