# web_ssl_management/tasks/check_response.yml
---
- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_fqdn is not defined


- name: Verify server responds with content from {{ ansible_fqdn }}
  uri:
    url: "https://{{ ansible_fqdn }}"
    method: GET
  register: uri_result
  retries: 5
  delay: 5
  until: "uri_result.content | length > 0"
  delegate_to: "{{ ansible_fqdn }}"
