---
- name: Gather service facts
  service_facts:

- name: Check httpd.socket status
  command: "systemctl is-active httpd.socket"
  register: httpd_socket_status
  changed_when: false
  failed_when: false

- name: Determine running web server
  set_fact:
    web_server: >-
      {{ 'httpd' if 
        ('httpd.service' in ansible_facts.services and ansible_facts.services['httpd.service'].state == 'running') or 
        (httpd_socket_status.rc == 0) 
      else 'nginx' if 'nginx.service' in ansible_facts.services and ansible_facts.services['nginx.service'].state == 'running' 
      else 'unknown' }}


- name: Set base web server-specific variables
  set_fact:
    ssl_conf: "{{ web_server_config[web_server].ssl_conf }}"
    service_name: "{{ web_server_config[web_server].service_name }}"
    cert_dir: "{{ web_server_config[web_server].cert_dir }}"
    key_dir: "{{ web_server_config[web_server].key_dir }}"
  when: web_server != 'unknown'


- name: Debug
  ansible.builtin.debug:
    var:
      - ssl_conf
      - service_name
      - cert_dir
      - key_dir
