# web_ssl_management/tasks/detect_webserver.yml
---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Determine running web server
  ansible.builtin.set_fact:
    running_web_server: >-
      {{ 'httpd' if 'httpd.service' in ansible_facts.services and ansible_facts.services['httpd.service'].state == 'running' else
      'nginx' if 'nginx.service' in ansible_facts.services and ansible_facts.services['nginx.service'].state == 'running' else
      'unknown' }}

- name: Set web_server variable based on ssl_action
  ansible.builtin.set_fact:
    web_server: >-
      {{ web_server_type if ssl_action == 'install' and web_server_type in ['httpd', 'nginx'] else running_web_server }}

- name: Set base web server-specific variables
  ansible.builtin.set_fact:
    cert_dir: "{{ web_server_config[web_server].cert_dir }}"
    key_dir: "{{ web_server_config[web_server].key_dir }}"
    service_name: "{{ web_server_config[web_server].service_name }}"
    ssl_conf: "{{ web_server_config[web_server].ssl_conf }}"
  when: web_server != 'unknown'

