# web_ssl_management/tasks/install_httpd.yml
---
- name: Install certificates and key
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: true
  loop:
    - { src: "{{ cert_files[0].path }}", dest: "{{ cert_dir }}/{{ ansible_fqdn }}.crt", mode: '0644' }
    - { src: "{{ key_files[0].path }}", dest: "{{ key_dir }}/{{ ansible_fqdn }}.key", mode: '0600' }
    - { src: "{{ ca_cert_file[0].path }}", dest: "{{ cert_dir }}/intermediate.crt", mode: '0644' }
  vars:
    cert_dir: "{{ web_server_config.httpd.cert_dir }}"
    key_dir: "{{ web_server_config.httpd.key_dir }}"

- name: Configure httpd SSL
  ansible.builtin.template:
    src: httpd_ssl.conf.j2
    dest: "{{ ssl_conf }}"
#    dest: "{{ ssl_conf_dir }}/{{ ansible_fqdn }}.conf"
    mode: '0644'
    backup: true
  notify: Restart web server
  vars:
#    ssl_conf_dir: "{{ web_server_config.httpd.ssl_conf_dir }}"
    ssl_conf: "{{ web_server_config.httpd.ssl_conf_files }}"

- name: Flush handlers to reload httpd immediately
  meta: flush_handlers

