---
- name: Fail if web_server is undefined
  fail:
    msg: "Variable web_server must be defined for install action"
  when: ssl_action == 'install' and web_server is not defined

- name: Set package list based on web_server
  set_fact:
    package_list: "{{ web_server_config[web_server].packages }}"
  when: ssl_action == 'install'

- name: Set task files based on web_server
  set_fact:
    install_task_file: "{{ 'install_httpd.yml' if web_server == 'httpd' else 'install_nginx.yml' }}"
    check_response_task_file: "{{ 'check_response_curl.yml' if ssl_action == 'install' else 'check_response.yml' }}"

- name: Install web server packages
  package:
    name: "{{ package_list }}"
    state: present
  when: ssl_action == 'install'
  notify: daemon_reload

- name: Flush handlers to reload daemon immediately
  meta: flush_handlers
    
- name: Include web server-specific installation tasks
  include_tasks: "{{ install_task_file }}"

- name: Enable and start web server
  service:
    name: "{{ web_server_config[web_server].service_name }}"
    state: started
    enabled: true

- name: Check HTTP response
  include_tasks: "{{ check_response_task_file }}"
