# web_ssl_management/tasks/install_nginx.yml
---
- name: Ensure certificate directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ cert_dir }}", mode: '0755' }
    - { path: "{{ key_dir }}", mode: '0700' }
  vars:
    cert_dir: "{{ web_server_config.nginx.cert_dir }}"
    key_dir: "{{ web_server_config.nginx.key_dir }}"

- name: Create full chain bundle
  ansible.builtin.copy:
    content: "{{ lookup('file', cert_files[0].path) + lookup('file', ca_cert_file[0].path) }}"
    dest: "{{ temp_dir }}/fullchain.pem"
    mode: '0644'
  vars:
    cert_dir: "{{ web_server_config.nginx.cert_dir }}"
    key_dir: "{{ web_server_config.nginx.key_dir }}"

- name: Install new certificates
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: true
  loop:
    - { src: "{{ temp_dir }}/fullchain.pem", dest: "{{ cert_dir }}/fullchain.pem", mode: '0644' }
    - { src: "{{ key_files[0].path }}", dest: "{{ key_dir }}/{{ ansible_fqdn }}.key", mode: '0600' }
  notify: Restart nginx server

- name: Configure Nginx SSL
  ansible.builtin.template:
    src: default.conf.j2
    dest: "{{ ssl_conf }}"
    backup: yes
  notify: Restart nginx server
  vars:
    ssl_conf: "{{ web_server_config.nginx.ssl_conf }}"
