# web_ssl_management/tasks/main.yml
---
- name: Run preliminary checks
  ansible.builtin.include_tasks: prechecks.yml

- block:
    - name: Prepare SSL certificates and Root CA
      ansible.builtin.include_tasks: prepare_certs.yml

    - name: Install web server and configure SSL
      ansible.builtin.include_tasks: install_web_server.yml
      when: ssl_action == 'install'

    - name: Reinstall web server certificates
      ansible.builtin.include_tasks: reinstall_web_server.yml
      when: ssl_action == 'reinstall'

  always:
    - name: Clean up temporary files
      ansible.builtin.include_tasks: cleanup.yml
      when: ssl_action in ['install', 'reinstall']

- name: Verify web server response
  ansible.builtin.include_tasks: check_response.yml
  when: ssl_action in ['install', 'reinstall']
