# web_ssl_management/tasks/install_nginx.yml
---
- name: Ensure certificate directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ cert_dir }}", mode: '0755' }
    - { path: "{{ key_dir }}", mode: '0700' }
  vars:
    cert_dir: "{{ web_server_config.nginx.cert_dir }}"
    key_dir: "{{ web_server_config.nginx.key_dir }}"

- name: Read certificate file
  ansible.builtin.slurp:
    src: "{{ cert_files[0].path }}"
  register: cert_content

- name: Read CA certificate file
  ansible.builtin.slurp:
    src: "{{ ca_cert_file[0].path }}"
  register: ca_cert_content

- name: Create full chain bundle
  ansible.builtin.copy:
    content: "{{ cert_content['content'] | b64decode }}\n{{ ca_cert_content['content'] | b64decode }}"
    dest: "{{ cert_dir }}/fullchain.pem"

- name: Install new key for {{ cert_dir }}/fullchain.pem
  ansible.builtin.copy:
    src: "{{ key_files[0].path }}"
    dest: "{{ key_dir }}/{{ ansible_fqdn }}.key"
    mode: "0600"
    remote_src: true

- name: Configure Nginx SSL
  ansible.builtin.template:
    src: nginx_ssl.conf.j2
    dest: "{{ web_server_config.nginx.ssl_conf_files }}"
    backup: yes
  notify: Restart web server

- name: Flush handlers to reload nginx immediately
  meta: flush_handlers

